# Generated by Django 2.2.6 on 2019-10-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.DateTimeField(null=True),
        ),
    ]
