# Generated by Django 2.2.6 on 2019-10-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_donation_is_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(null=True),
        ),
    ]
